version: "3.9"

services:
  postgres:
    image: postgres:18.1
    container_name: demoapi-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: demoapi
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    volumes:
      - postgres_data:/var/lib/postgresql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demoapi-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=demoapi;Username=demo;Password=demo
    depends_on:
      - postgres

volumes:
  postgres_data:
